In [4]:
import sys
basepath = 'd:\\Users\\serfe\\Documents\\GitHub\\GENIE\\Code'
sys.path.append(basepath)
import numpy as np

# 1. install_dependencies.txt

# 2. make_initial_files.py

In [6]:
# Creates region.npz, stations.npz and 1d_velocity_model.npz
!python make_initial_files.py
region = np.load(basepath + '\\' + 'region.npz')
stations = np.load(basepath + '\\' + 'stations.npz')
velocity_model_1d = np.load(basepath + '\\' + '1d_velocity_model.npz')

Loading configuration from 'config.yaml'...
Setting up time range...
Connecting to IRIS client...
Setting up region based on configuration...
Extracting station data...
Determining base path for saving files...
Saving files...
All files saved successfully!
✔ Script execution: Done


In [9]:
for key in region:
    print(key)
    print(region[key])

lat_range
[18.8 20.3]
lon_range
[-156.1 -154.7]
depth_range
[-40000   5000]
deg_pad
0.25
num_grids
5
n_spatial_nodes
500
years
[2018 2019 2020 2021 2022 2023]
load_initial_files
[False]
use_pretrained_model
['None']


In [12]:
for key in stations:
    print(key)
    print(stations[key])

locs
[[ 1.89793600e+01 -1.55667897e+02  2.51000000e+02]
 [ 1.91554130e+01 -1.55462112e+02  3.40000000e+01]
 [ 1.91645180e+01 -1.55749057e+02  1.59200000e+03]
 [ 1.92375030e+01 -1.55397507e+02  4.01000000e+02]
 [ 1.92483780e+01 -1.55498982e+02  9.06000000e+02]
 [ 1.92633000e+01 -1.55869000e+02  5.24000000e+02]
 [ 1.92812300e+01 -1.55224645e+02  1.76000000e+02]
 [ 1.92858630e+01 -1.55129087e+02  4.40000000e+01]
 [ 1.92962530e+01 -1.55307480e+02  7.24000000e+02]
 [ 1.93333950e+01 -1.55385650e+02  8.36000000e+02]
 [ 1.93356600e+01 -1.55301105e+02  9.35000000e+02]
 [ 1.93398250e+01 -1.55874496e+02  3.08000000e+02]
 [ 1.93536900e+01 -1.55664418e+02  3.02700000e+03]
 [ 1.93715670e+01 -1.55263462e+02  1.05100000e+03]
 [ 1.93720670e+01 -1.55457228e+02  1.52400000e+03]
 [ 1.93735680e+01 -1.55240608e+02  1.04600000e+03]
 [ 1.93737850e+01 -1.55215500e+02  9.94000000e+02]
 [ 1.93794470e+01 -1.55169297e+02  9.33000000e+02]
 [ 1.93840450e+01 -1.55101578e+02  8.26000000e+02]
 [ 1.93848600e+01 -1.55125

In [13]:
for key in velocity_model_1d:
    print(key)
    print(velocity_model_1d[key])

Depths
[-40000 -35000 -30000 -25000 -20000 -15000 -10000  -5000      0   5000]
Vp
[8200 8200 8150 8100 8050 7400 6800 6100 2900 2900]
Vs
[4700 4700 4650 4600 4600 4200 3800 3400 1800 1800]


# 3. assemble_network_data.py